services:
  - type: web
    name: connectify-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://your-frontend-domain.vercel.app,https://your-frontend-domain.netlify.app
